name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: tallyscesargb
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
